# Uncomment this line to define a global platform for your project
# platform :ios, '10.0'

target 'FullProfile' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'Alamofire', '~> 4.1'

post_install do |installer|
installer.pods_project.targets.each do |target|
target.build_configurations.each do |config|
config.build_settings['SWIFT_VERSION'] = '3.0'
end
end
end

pod 'OAuthSwift', '~> 1.1.0'

pod 'AeroGearHttp'

pod 'p2.OAuth2', '~> 3.0'

pod 'SwiftyJSON'

#pod 'AeroGearOAuth2'

#pod 'AeroGearOAuth2'

  # Pods for FullProfile

  target 'FullProfileTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FullProfileUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
